# Generated by Django 3.1.2 on 2021-01-12 04:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(choices=[('Pollo Cocido', 'Pollo Cocido'), ('Arroz Cocido', 'Arroz Cocido'), ('Spaghetti Carbonara', 'Spaghetti Carbonara')], max_length=200)),
                ('food_portion_quantity', models.IntegerField()),
                ('food_macro', models.CharField(choices=[('Proteina', 'Proteina'), ('Carbohidratos', 'Carbohidratos')], max_length=200)),
                ('food_serving_quantity', models.IntegerField()),
                ('macro_total', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
