# Generated by Django 3.1.2 on 2021-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_journal',
            name='macro_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
