# Generated by Django 3.1.2 on 2021-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_auto_20210111_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_journal',
            name='uuid',
            field=models.IntegerField(),
        ),
    ]
